name: CI Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y fonts-noto-cjk latexmk texlive-fonts-recommended texlive-lang-chinese texlive-xetex

      - name: Build docs
        working-directory: .
        run: make html

      - name: Build PDF
        working-directory: .
        run: make latexpdf

